[icons]
name = "awesome"

[icons.overrides]
net_down = ""
cpu = ""

[theme]
name = "plain"

[theme.overrides]
#separator = "<span font='12.3'></span>"
separator = ""

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
buttons = ["play"]

[[block]]
block = "cpu"
interval = 1
format = " CPU {barchart} {utilization}"

[[block]]
block = "net"
device = "wlp2s0"
format = "{ssid} {ip} {speed_down}"
interval = 5
use_bits = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "used"
unit = "GiB"
format = "{icon} {available} {unit}"

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
device = "BAT0"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
