[icons]
name = "awesome"

[icons.overrides]
net_down = ""
music="♪ "
cpu = ""

[theme]
file = "/home/rab1t/.config/i3/mytheme.toml"

[theme.overrides]
#separator = "<span font='12'></span>"
separator = "<span font='13'>\ue0ba</span>"
#separator = ""

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]

[[block]]
block = "cpu"
interval = 1
format = "CPU {utilization} {barchart}"

[[block]]
block = "memory"
#format_mem = "M {Mup}% S {SUp}%"
format_mem = "{Mup}%"
icons = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "net"
format = "{speed_down}"
interval = 5
use_bits = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "used"
unit = "GiB"
format = "{icon} {available} {unit}"

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
device = "BAT0"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
