[icons]
name = "awesome"

[icons.overrides]
music="♪"

[theme]
file = "/home/nya/.config/i3/mytheme.toml"
#name = "semi-native"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]

[[block]]
block = "cpu"
interval = 1
format = " CPU {utilization} {barchart}"
icons_format = ""

[[block]]
block = "memory"
#format_mem = "M {Mup}% S {SUp}%"
#format_mem = "{Mup}%"
icons = true
interval = 5
warning_mem = 0
warning_swap = 0
critical_mem = 95
critical_swap = 95

[[block]]
block = "net"
device="wlp0s20f3"
interval = 5
#format = "{ip} {speed_down;M*b}"
format = "{ip}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "used"
unit = "GB"
format = "{icon} {available}"
alert = 0

[[block]]
block = "sound"
format = "{volume:5#110} {volume}"

[[block]]
block = "battery"
driver = "upower"
device = "BAT0"
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
